[package]
name = "to-do"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = "4.9.0"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.39.3", features = ["full"] }
dotenv = "0.15"
mongodb = "3.0.1"
bcrypt = "0.15.1"
futures-util = "0.3"
jwt-simple = "0.12.10"
validator = { version = "0.14", features = ["derive"] }
validator_derive = "0.14"
actix-cors = "0.7.0"
futures = "0.3.30"
actix-service = "2.0.2"
actix-web-httpauth = "0.8.2"
actix-http = "3.9.0"
jsonwebtoken = "9.3.0"
